### ISSUE TITLE
请问使用uni-app 应用能打包成ios和安卓应用中使用吗

### ISSUE THREAD

**Issue by BEIBEI123** [TencentCloudBase/cloudbase-templates#22]
请问使用uni-app应用能打包成ios和安卓应用可以正常使用吗

**Comment by qinmudi** [comment]
你好，暂时还不支持安卓和IOS端，内部已经加紧在做端的sdk支持了，后面有消息会在官网通知？

**Comment by hbcui1984** [comment]
> 请问使用uni-app应用能打包成ios和安卓应用可以正常使用吗

可以的，uni-app本身是支持跨平台的，可以发行成App/H5/小程序，uni-app基于腾讯cloudbase发布了深度优化的serverless方案，即uniCloud，详情参考：https://uniapp.dcloud.net.cn/uniCloud/README
