### ISSUE TITLE
 Nest 模板发布到腾讯云报错

### ISSUE THREAD

**Issue by DaZiYuan** [TencentCloudBase/cloudbase-templates#35]
{"requestId":"34b240119b52fd8777c4dce49142ebdc","code":"INVOKE_FUNCTION_FAILED","message":"Error: Cannot find module './dist/main'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:508:25)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at Object.<anonymous> (/var/user/app.js:2:14)\n    at Module._compile (internal/modules/cjs/loader.js:701:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)\n    at Module.load (internal/modules/cjs/loader.js:600:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:531:3)"}

**Comment by DaZiYuan** [comment]
重现步骤：
https://github.com/TencentCloudBase/cloudbase-framework
![image](https://user-images.githubusercontent.com/80653/96204618-5b3af180-0f97-11eb-8bef-0cf8445b7b4c.png)

**Comment by binggg** [comment]
收到，感谢反馈

**Comment by binggg** [comment]
已经修复
