### ISSUE TITLE
Koa,Nest,Egg的示例模版线上链接访问都是报错的状态？

### ISSUE THREAD

**Issue by seymoe** [TencentCloudBase/cloudbase-templates#38]
Koa,Nest,Egg的示例模版线上链接访问都是报错的状态？

**Comment by seymoe** [comment]
[https://github.com/TencentCloudBase/cloudbase-framework/commit/7c3c37c5bc81910131ae56b9bc9a2f4b7146e43c
](https://github.com/TencentCloudBase/cloudbase-framework/commit/7c3c37c5bc81910131ae56b9bc9a2f4b7146e43c
)
已解决，关闭

**Comment by binggg** [comment]
感谢支持
