### ISSUE TITLE
nuxt-ssr模板部署后，报跨域问题

### ISSUE THREAD

**Issue by cmlanche** [TencentCloudBase/cloudbase-templates#42]
浏览器中错误提示:
Access to XMLHttpRequest at 'https://tcb-api.tencentcloudapi.com/web?env=xxx' from origin 'https://tuijianjunn-0g8hzljsb924d8bd.service.tcloudbase.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by chhpt** [comment]
登录云开发控制台，在安全配置页面中，将域名 tuijianjunn-0g8hzljsb924d8bd.service.tcloudbase.com 添加到 Web 安全域名中
