### ISSUE TITLE
nuxt-ssr的版本模板怎么把cloudfunctions里面的nuxt-ssr-echo在本地跑起来

### ISSUE THREAD

**Issue by cmlanche** [TencentCloudBase/cloudbase-templates#43]
现在在本地跑npm run dev，/nuxt-ssr-echo接口无法调用，应该是这个接口服务没有启动，请问怎么启动呢？

**Comment by chhpt** [comment]
/nuxt-ssr-echo 是云端的访问地址，不是本地的地址，本地无法直接运行云函数，可以参考 Koa/Express 的本地开发 Demo。
