### ISSUE TITLE
nuxt-ssr template   控制台报语法问题

### ISSUE THREAD

**Issue by Marcnuth** [TencentCloudBase/cloudbase-templates#44]
SyntaxError: Unexpected token < in JSON at position 0
_callee$ @ client.js?06a0:96

**Comment by chhpt** [comment]
未发现报错问题，请提供具体的复现步骤

**Comment by liiil825** [comment]
出现同样问题。
复现步骤：
```
tcb new nuxt-ssr nuxt-ssr
cd nuxt-ssr
npm i
npm run dev
```
运行环境：
macos 11.0.1
node: v12.20.0

**Comment by liiil825** [comment]
复现步骤里函数已经提前部署了

**Comment by chhpt** [comment]
@liiil825 demo 中会请求 /nuxt-ssr-echo/ 路径，本地开发没有处理 /nuxt-ssr-echo/ 请求，就会导致报错，你可以在本地开发时进行适配，或者直接请求线上。
