### ISSUE TITLE
部署express-templates，发现静态文件public的访问地址有问题，官方例子也有问题

### ISSUE THREAD

**Issue by evinLiang** [TencentCloudBase/cloudbase-templates#45]

**Comment by chhpt** [comment]
麻烦说明具体的问题表现，并提供复现步骤

**Comment by evinLiang** [comment]
> 麻烦说明具体的问题表现，并提供复现步骤

打开官方的express的demo链接[https://framework.service.tcloudbase.com/express-starter/](url)，控制台报`GET https://framework.service.tcloudbase.com/stylesheets/style.css net::ERR_ABORTED 404`怎样可以避免这种报错，估计是express的public静态文件路径和云函数路径问题，云函数路径会在访问链接再加上云函数名作为路径

**Comment by binggg** [comment]
引用路径的问题，我们修复下 

https://github.com/TencentCloudBase/cloudbase-templates/blob/master/express-starter/views/layout.jade#L5

**Comment by binggg** [comment]
已修复

**Comment by wx-wangxiang** [comment]
还是有问题，KOA模板报404，我按你的方法把'/stylesheets/style.css'前面的'/'去掉还是报错，但是把云函数名拼接到静态文件地址前面就能正常访问了，这样"cloudfunction_name/stylesheets/style.css"

**Comment by binggg** [comment]
@wx-wangxiang 我看看

**Comment by wx-wangxiang** [comment]
> @wx-wangxiang 我看看

你的改法在本地可以，发布到线上后因为路径里多了一个云函数名称，所以静态资源会报错

**Comment by binggg** [comment]
@wx-wangxiang不会啊，你看下官方的演示链接

https://framework.service.tcloudbase.com/express-starter/
