### ISSUE TITLE
nuxt-ssr 自定义域名怎么正确的绑定到根目录

### ISSUE THREAD

**Issue by liiil825** [TencentCloudBase/cloudbase-templates#48]
问题：为了绑定到自定义域名的根目录，现将HTTP访问服务加了两个访问路径（`/`, `/nuxt-ssr`），能否通过正确配置nuxt.config.js文件后，只保留一个 `/`
尝试修改修改配置 `nuxt.config.js` 文件属性`router.base` 和 `build.publicPath`，要么访问不到页面，要么页面中静态js资源文件无法访问

请问怎么配置能只保留一个HTTP访问触发器？还是必须有两条

**Comment by binggg** [comment]
HTTP访问服务加了两个访问路径（/, /nuxt-ssr）这里是怎么配置的

**Comment by liiil825** [comment]
进入腾讯云开发控制台
环境 -> HTTP访问服务 -> 新建

**Comment by binggg** [comment]
nuxt 配置文件修改 router.base 和 build.publicPath，去掉原来的 nuxt-ssr

同时需要在 `cloudbaserc.json` 中修改 path 指向
```
    "plugins": {
      "client": {
        "use": "@cloudbase/framework-plugin-nuxt",
        "inputs": {
          "path": "/",
          "memory": 512
        }
      },
```
