### ISSUE TITLE
Java 模板 README 中关于开发命令及配置的错误描述

### ISSUE THREAD

**Issue by moeyui1** [TencentCloudBase/cloudbase-templates#50]
![image](https://user-images.githubusercontent.com/11503525/104405093-23901580-5597-11eb-8502-a6dd7c5174a9.png)

Java 模板缺少 package.json 应该不支持如上的命令把？同样在 PHP 的模板中也有这样的内容。

**Comment by binggg** [comment]
确实，需要删除下

**Comment by binggg** [comment]
已经删除
