### ISSUE TITLE
如何基于部署的代码，进行自己代码的修改

### ISSUE THREAD

**Issue by sytpb** [TencentCloudBase/cloudbase-templates#55]
我部署了一react 实例，如何基于这个实例云增加修改自己的代码？

**Comment by binggg** [comment]
目前可以在应用管理界面找到来源的git地址

```
git pull $sourceGit
cd $workdir
# 修改代码

# CLI 部署
npm i @cloudbase/cli -g
# 执行部署，环境id 可通过参数传递，也可以修改cloudbaserc.json配置文件
tcb framework deploy -e $envId 
```

**Comment by sytpb** [comment]
谢谢，追问一下

我看到二个方式初始化项目一个是  

cloudbase init --template react-starter

另一个是cloudbase new react-app react-starter

有什么区别？

**Comment by binggg** [comment]
这两种没啥区别，new 是新的命令，init 会逐渐废弃

**Comment by sytpb** [comment]
第二种方式遇到一个问题，直接启动后会报错，
export const envId = window._tcbEnv.TCB_ENV_ID;
export const region = window._tcbEnv.TCB_REGION;

这二个是undefined ,
export const envId = "cloud-onetown-****c";
改成这样后，再启动还是有一个错，但是我不知道什么问题。
![image](https://user-images.githubusercontent.com/12178686/109612459-b8ac9500-7b6a-11eb-8303-ed2165cf2351.png)

**Comment by binggg** [comment]
嗯嗯，在public/index.html 中引入了一个初始化的js，会自动写入环境id和地域等信息，在云端的部署的时候可以不用修改代码即可部署

这个在本地启动的时候暂时还访问不到，如果是二次开发需要本地开发，可以考虑去掉这个js，用手动填写环境id的方式

**Comment by binggg** [comment]
我们在考虑推出一个 tcb dev 或者 tcb serve 来解决本地开发的问题

**Comment by sytpb** [comment]
哦，再追问二个  ：） 

![image](https://user-images.githubusercontent.com/12178686/109613801-a6335b00-7b6c-11eb-88e7-bb71f85c1620.png)

这三个有什么区别？ 

![image](https://user-images.githubusercontent.com/12178686/109614125-2b1e7480-7b6d-11eb-8ee5-992347f0b411.png)


cloudbase framework deploy 这个命令会自动编译打包？ ，不用执行 yarn build ?

npm run deploy 上线部署 是什么意思？

**Comment by binggg** [comment]
1. 一个比较复杂的react 项目，暂时没有维护
2. 支持 TS的 react项目
3. js 版本react项目

npm run deploy 执行的也是 cloudbase framework deploy 命令
在 cloudbaserc.json 中我们实际上配置了如何build
