### ISSUE TITLE
'cloudbase framework deploy '  happen error 

### ISSUE THREAD

**Issue by sytpb** [TencentCloudBase/cloudbase-templates#56]
![image](https://user-images.githubusercontent.com/12178686/109644216-27e8b000-7b90-11eb-9967-90711f4b69f0.png)

**Comment by binggg** [comment]
看起来是依赖安装的问题，可以看下手动安装依赖是否可以成功

**Comment by sytpb** [comment]
![image](https://user-images.githubusercontent.com/12178686/109651460-87978900-7b99-11eb-9975-c5cdcb7945e6.png)
![image](https://user-images.githubusercontent.com/12178686/109651510-941be180-7b99-11eb-89b0-ab00bc6aaecb.png)

本地yarn build 会出错。

**Comment by binggg** [comment]
这里可以把 CI=false 去掉，这种写法在windows不太兼容

**Comment by sytpb** [comment]
build 成功，

![image](https://user-images.githubusercontent.com/12178686/109654628-5de06100-7b9d-11eb-801c-021fbb88b8f1.png)
部署也成功，

但是 
![image](https://user-images.githubusercontent.com/12178686/109654891-b4e63600-7b9d-11eb-9d23-d45c64f31d38.png)

**Comment by binggg** [comment]
tcb hosting deploy 这种没有走应用的流程，可以考虑用 tcb framework deploy 来部署，这样应用列表里面会有

**Comment by sytpb** [comment]
tcb hosting deploy 成功给出网址，正常是不是可以访问的？ 
打开是错误的
![image](https://user-images.githubusercontent.com/12178686/109754297-b4da4a80-7c1e-11eb-8f15-c62abe0afe2f.png)

**Comment by binggg** [comment]
路径要对，要看这个路径下有没有 index.html

**Comment by sytpb** [comment]
![image](https://user-images.githubusercontent.com/12178686/109756639-451a8e80-7c23-11eb-92a4-bf5e99096374.png)

![image](https://user-images.githubusercontent.com/12178686/109756651-49df4280-7c23-11eb-8238-ef0e07eb0bc9.png)

![image](https://user-images.githubusercontent.com/12178686/109756536-14d2f000-7c23-11eb-9216-9bad0163d16f.png)

**Comment by binggg** [comment]
多加个/



---Original---

**Comment by sytpb** [comment]
去掉 '/' 还是一样的， 
![image](https://user-images.githubusercontent.com/12178686/109758142-15b95100-7c26-11eb-9bce-2147b362e639.png)  
这个路径不对。。。

**Comment by sytpb** [comment]
![image](https://user-images.githubusercontent.com/12178686/109758377-72b50700-7c26-11eb-9b3b-f676861ac209.png)

tcb hosting deploy .    /LarkOfficeSite      ....    部署到指定路径的话，上面cloudpath 是不是得改成一样的文件夹（LarkOfficeSite）？

**Comment by binggg** [comment]
是的

**Comment by sytpb** [comment]
问题解决，谢谢耐心解答！
配置文件 cloudbaserc.json  .env   都改成自己要上传的目录（非根目录） 重新build , 重新上传 ， 域名+路径访问网页正常
![image](https://user-images.githubusercontent.com/12178686/109766661-6edab200-7c31-11eb-9f6f-716a79d656cc.png)
![image](https://user-images.githubusercontent.com/12178686/109766733-87e36300-7c31-11eb-9fb8-a18c079f6544.png)

建议这个不要硬编码。
