### ISSUE TITLE
thinkjs多模块项目启动报错

### ISSUE THREAD

**Issue by stys35** [TencentCloudBase/cloudbase-templates#59]
thinkjs多模块项目模式启动报错

$ cloudbase new tcbstarter thinkjs-starter
$ tcb

多模块化以后：
  "thinkjs": {
    "metadata": {
      "name": "thinkjs-starter",
      "description": "application created by thinkjs",
      "author": "lizheming <i@imnerd.org>",
      "babel": false,
      "defaultModule": "home"
    },
    "projectName": "thinkjs-starter",
    "clone": false,
    "isMultiModule": true
  }

具体异常如下：

错误码: INVOKE_FUNCTION_FAILED
错误信息: Error: EROFS: read-only file system, mkdir '/var/user/logs' at Object.mkdirSync (fs.js:752:3) at Object.mkdirsSync (/var/user/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9) at DateRollingFileStream._renewWriteStream (/var/user/node_modules/streamroller/lib/RollingFileWriteStream.js:402:8) at new RollingFileWriteStream (/var/user/node_modules/streamroller/lib/RollingFileWriteStream.js:107:10) at new DateRollingFileStream (/var/user/node_modules/streamroller/lib/DateRollingFileStream.js:23:5) at appender (/var/user/node_modules/log4js/lib/appenders/dateFile.js:27:19) at Object.configure (/var/user/node_modules/log4js/lib/appenders/dateFile.js:57:10) at clustering.onlyOnMaster (/var/user/node_modules/log4js/lib/appenders/index.js:63:27) at Object.onlyOnMaster (/var/user/node_modules/log4js/lib/clustering.js:74:50) at createAppender (/var/user/node_modules/log4js/lib/appenders/index.js:61:21)

**Comment by binggg** [comment]
日志目录需要配置下，只有 /tmp 目录是可以写的
