### ISSUE TITLE
Nuxt+SSR的首次打开，云函数的冷启动太慢了。经常访问不到服务器。之后在刷新就可以了。可以怎么优化呢？

### ISSUE THREAD

**Issue by jveay** [TencentCloudBase/cloudbase-templates#63]

**Comment by binggg** [comment]
如果熟悉docker的话可以用云托管插件来部署，支持常驻进程

**Comment by jveay** [comment]
感谢回复。云托管部署成功但是和云函数不同域名会导致跨域。除了配置请求代理还有不用跨域又可以使用云数据库或云函数的办法吗？

**Comment by jveay** [comment]
这边使用了云函数的插件和容器的插件。云托管的默认域名和云函数的域名不一样。

**Comment by binggg** [comment]
云托管也可以通过和云函数同样的http访问服务的域名来访问
