### ISSUE TITLE
Vue模板建议提供默认envId参数

### ISSUE THREAD

**Issue by BA3000** [TencentCloudBase/cloudbase-templates#66]
直接使用`cloudbase new vue-app vue`创建的Vue应用无法直接通过`npm run dev`在本地预览。执行指令后浏览器显示为空白，并且在控制台报如下错误：

![image](https://user-images.githubusercontent.com/35647825/120257028-fcc24980-c2c1-11eb-8a37-90ec5a030dd3.png)

这是因为在`main.js`中的第七行`export const envId = window._tcbEnv.TCB_ENV_ID;`在本地运行的时候为空，建议提供默认参数，如：

```javascript
window._tcbEnv = window._tcbEnv || {TCB_ENV_ID:"hello-cloudbase-6g75912970589688"};
```

并且在附近注释提醒用户修改TCB_ENV_ID。

**Comment by binggg** [comment]
感谢建议，欢迎提PR

**Comment by chhpt** [comment]
closed #67
