### ISSUE TITLE
对序列化的params 对象 本地测试成功 云函数就是获取不了

### ISSUE THREAD

**Issue by baiheinet** [TencentCloudBase/cloudbase-templates#68]
![image](https://user-images.githubusercontent.com/900786/120609781-1d86cc80-c485-11eb-8917-e9dbc8473dc8.png)
 
本地 
![image](https://user-images.githubusercontent.com/900786/120609862-31cac980-c485-11eb-831f-701e782fbb9f.png)
云函数
![image](https://user-images.githubusercontent.com/900786/120609908-4018e580-c485-11eb-85d9-3298961da806.png)
请问怎么解决啊！！

**Comment by chhpt** [comment]
@baiheinet 请提供有效的请求 ID，环境 ID 信息

PS：看你的 message，云函数可能没有执行成功

**Comment by baiheinet** [comment]
> @baiheinet 请提供有效的请求 ID，环境 ID 信息
> 
> PS：看你的 message，云函数可能没有执行成功

![image](https://user-images.githubusercontent.com/900786/120771431-c7338f80-c551-11eb-81a5-15185c709072.png)
![image](https://user-images.githubusercontent.com/900786/120771497-d9153280-c551-11eb-8f71-834d819e3d7c.png)

**Comment by chhpt** [comment]
@baiheinet 云函数执行成功，说明问题和平台无关。不太理解这里存在的问题，麻烦详细说明具体出现的问题

**Comment by baiheinet** [comment]
> @baiheinet 云函数执行成功，说明问题和平台无关。不太理解这里存在的问题，麻烦详细说明具体出现的问题

很简单啊 就是get 方式的查询参数 data 本地测试可以接受 云函数接受不到啊 data null

**Comment by chhpt** [comment]
@baiheinet 云函数的执行逻辑与一般的 HTTP Server 不同，需要自行兼容
