### ISSUE TITLE
你好，模板 `uni-app-starter` 不存在,可以建一个吗

### ISSUE THREAD

**Issue by uspear** [TencentCloudBase/cloudbase-templates#75]
你好，模板 `uni-app-starter` 不存在,可以建一个吗？
采用uniapp+cloudbase模式

**Comment by binggg** [comment]
uniapp 这里依赖 unicloud 自己开通云服务，使用CLI的体验不是很好

**Comment by uspear** [comment]
还是建议建一个好，unicloud的体验不好，封装后性能不行，首次请求都要3000ms，如果是联合查询，速度更慢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Booker ***@***.***&gt;; 
发送时间: 2021年12月20日(星期一) 下午3:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TencentCloudBase/cloudbase-templates] 你好，模板 `uni-app-starter` 不存在,可以建一个吗 (Issue #75)





 
uniapp 这里依赖 unicloud 自己开通云服务，使用CLI的体验不是很好
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
